services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
    depends_on:
      - redis